[package]
name = "malware"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
chrono = "0.4.31"
rust-crypto = "0.2.36"
walkdir = "2.5.0"
sysinfo = "0.32.0"
build_html = "2.5.0"
serde_json = "1.0.128"
serde = { version = "1.0", features = ["derive"] }
lettre = "0.11.9"
lettre_email = "0.9.4"
whoami = "1.5.2"
soloud = "1.0.5"
get_if_addrs = "0.5.3"

[build-dependencies]
bindgen = "0.65.1"

